# ============================================
# Configuration de la watchlist (FR)
# - categorie : "linear" (USDT), "inverse" (USD) ou "both"
# - funding_min / funding_max : bornes sur le taux de funding (valeurs décimales)
#   Exemples : 0.0001 = 0.01%   |   -0.0002 = -0.02%
# - volume_min_millions : volume minimum en millions (ex: 5.0 = 5M USDT)
# - spread_max : spread maximum autorisé (ex: 0.003 = 0.30%)
# - volatility_min : volatilité minimum autorisée (ex: 0.002 = 0.20%) [NOUVEAU]
# - volatility_max : volatilité maximum autorisée (ex: 0.007 = 0.70%) [NOUVEAU]
# - limite : nombre max de paires à afficher (après tri par |funding| décroissant)
# 
# PRIORITÉ : Variables ENV > volume_min_millions (fichier)
# ============================================

categorie: "linear"      # "linear" | "inverse" | "both"
funding_min: 0.0001     # ex: 0.0001 pour >= 0.01%  | null = pas de min
funding_max: null        # ex: 0.0005 pour <= 0.05%  | null = pas de max
volume_min_millions: 100 # ex: 5.0 pour >= 5M USDT | null = pas de min
# Normalisation: spread exprimé en ratio (0.003 = 0.30%)
spread_max: null        # ex: 0.003 pour <= 0.30% | null = pas de filtre
volatility_min: null     # ex: 0.002 pour >= 0.20% | null = pas de min [NOUVEAU]
volatility_max: null    # ex: 0.007 pour <= 0.70% | null = pas de max [NOUVEAU]
volatility_ttl_sec: 60  # TTL du cache volatilité (secondes)
                        # Recalcul de la volatilité toutes les 60 secondes
limite: 20               # ex: 10  | null = pas de limite
funding_time_min_minutes: null   # Optionnel: minimum 30 minutes avant funding
funding_time_max_minutes: 1400 # Optionnel: maximum 120 minutes avant funding

# ============================================
# Configuration du système de poids
# ============================================
# Coefficients pour le calcul du score pondéré
# Le score est calculé selon la formule :
# score = abs(funding_rate) * weights.funding
#       + log(volume + 1) * weights.volume  
#       - spread * weights.spread
#       - volatility * weights.volatility
weights:
  funding: 1000    # Poids du funding rate (valeur absolue) - CRITÈRE PRINCIPAL (x10)
  volume: 0.01     # Poids du volume (logarithme) - critère secondaire (x0.1)
  spread: 0.1       # Poids du spread (soustrait) - critère secondaire (x0.1)
  volatility: 0.05 # Poids de la volatilité (soustrait) - critère secondaire (x0.1)
  top_symbols: 20   # Nombre maximum de symboles à conserver après tri

# ============================================
# Configuration de l'affichage
# ============================================
display_interval_seconds: 1 # Intervalle d'affichage de la watchlist (secondes)